version: '3'

services:

  challenge-api:
    image: challenge-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=challenge-api
    ports:
      - "3000:3000"
    volumes:
      - ./challenge-api:/app/challenge-api
      - ./deno.json:/app/deno.json
      - ./import_map.json:/app/import_map.json
    networks:
      - default
    environment:
      - PORT=3000
      - BROKER_HOST=broker
      - BROKER_PORT=1883

  disturbance-api:
    image: disturbance-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=disturbance-api
    ports:
      - "3001:3001"
    volumes:
      - ./disturbance-api:/app/disturbance-api
      - ./deno.json:/app/deno.json
      - ./import_map.json:/app/import_map.json
    networks:
      - default
    environment:
      - PORT=3001
      - BROKER_HOST=broker
      - BROKER_PORT=1883

  route-api:
    image: route-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=route-api
    ports:
      - "3002:3002"
    volumes:
      - ./route-api:/app/route-api
      - ./deno.json:/app/deno.json
      - ./import_map.json:/app/import_map.json
    networks:
      - default
    environment:
      - PORT=3002
      - BROKER_HOST=broker
      - BROKER_PORT=1883

  broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./broker/log:/mosquitto/log
      - data:/mosquitto/data

volumes:
  data:
    name: "mqtt-broker-data"

networks:
  default:
