name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  deno:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 #v1.1.2
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test --allow-env
